CREATE DATABASE SoftUni

CREATE TABLE Towns
(
Id INT IDENTITY(1,1) PRIMARY KEY,
[Name] VARCHAR(20) NOT NULL
)

CREATE TABLE Adresses
(
Id INT IDENTITY(1,1) PRIMARY KEY,
AdressText VARCHAR(50) NOT NULL,
TownId INT NOT NULL

CONSTRAINT FK_Adresses_Towns
	FOREIGN KEY (TownId)
		REFERENCES Towns(Id)
)

CREATE TABLE Departments 
(
Id INT IDENTITY(1,1) PRIMARY KEY,
[Name] VARCHAR(30) NOT NULL
)

CREATE TABLE Employees
(
Id INT IDENTITY(1,1) PRIMARY KEY,
FirstName VARCHAR(15) NOT NULL,
MiddleName VARCHAR(15) NOT NULL,
LastName VARCHAR(15) NOT NULL,
JobTitle VARCHAR(30) NOT NULL,
DepartmentId INT NOT NULL,
HireDate DATE NOT NULL,
Salary DECIMAL(7,2) NOT NULL,
AdressId INT

CONSTRAINT FK_Employees_Departments
	FOREIGN KEY (DepartmentId)
		REFERENCES Departments(Id),

CONSTRAINT FK_Employees_Adresses
	FOREIGN KEY (AdressId)
		REFERENCES Adresses(Id)
)
